on:
  pull_request: ~
  push:
    branches:
      - "main"

jobs:
  static:
    name: Static analysis

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download dependencies
        run: composer update --no-interaction --prefer-dist --optimize-autoloader

      - name: PHPStan
        run: ./vendor/bin/phpstan

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation
